spring.datasource.url=jdbc:postgresql://localhost:5432/crowdfund
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

app.jwt.secret=Y29ycG9yYXRlLWFuZC1zZXJ2ZS1jcm93ZGZ1bmRpbmctc2VjcmV0LWtleS0yMDI0
app.jwt.expiration=86400000